### ISSUE TITLE
Update home page of wiki to be not redundant with sub-pages

### ISSUE THREAD

**Issue by AnneCarpenter** [jccaicedo/Distributed-CellProfiler#44]
The home page here: https://github.com/jccaicedo/Distributed-CellProfiler/wiki shows 4 steps which overlap the individual pages for each step.

**Comment by AnneCarpenter** [comment]
I suspect the content of Basic overview might want to live on the Home page instead as part of this cleanup?

**Comment by bethac07** [comment]
That's fine with me; the home page is literally just the readme with 2 lines changed so we can always regenerate it from that if need be.
